name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-contracts:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - name: "Test contracts"
        uses: docker://hirosystems/clarinet:0.23.0
        with:
          args: test --manifest-path=contracts/Clarinet.toml

  test-wallet-snapshot:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    defaults:
      run:
        working-directory: packages/wallet-snapshot

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

  sales-report-tool:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    defaults:
      run:
        working-directory: packages/sales-report-tool

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
