name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-contracts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - name: Install clarinet
        run: |
          wget -L https://github.com/hirosystems/clarinet/releases/download/v0.19.1/clarinet-linux-x64.tar.gz
          tar xzf clarinet-linux-x64.tar.gz
          chmod +x ./clarinet
          mkdir -p "$HOME/.local/bin"
          mv ./clarinet "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Test contracts
        run: clarinet test

  test-wallet-snapshot:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: packages/wallet-snapshot

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.21.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
