name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-contracts:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - name: "Test contracts"
        uses: docker://hirosystems/clarinet:0.23.0
        with:
          args: test --manifest-path=contracts/Clarinet.toml

  test-wallet-snapshot:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: packages/wallet-snapshot

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.21.1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
